services:
  dns:
    image: ghcr.io/plutoploy/dns-handling:latest
    container_name: dns_records
    ports: 
      - "8080:8080"
    env_file:
      - .env
    networks:
      - server

networks:
  server:
    name: server
