[tools]
go = "latest"
claude-code = "latest"
node = "latest"
betterleaks = "latest"
codex = "latest"
action-validator = "latest"
actionlint = "latest"

[deps]
go = { auto = true }

[settings]
experimental = true
